package coupon.sys.core.beans;

import java.io.Serializable;
import java.util.Collection;

import coupon.sys.core.exceptions.CouponSystemExceptions;
import coupon.sys.core.exceptions.CryptoHashException;
import coupon.sys.core.utils.CryptoHashAlgorithms;

/**
 * This class is for creating the company object to use with the different
 * company related methods.
 * 
 * @author Julio Hernan Trajtemberg
 * @version 1.0 September 18, 2018.
 */

public class Company implements Serializable {

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** The id. */
	private long id;

	/** The name. */
	private String name;

	/** The password. */
	private String password;

	/** The email. */
	private String email;

	/** The coupons. */
	private Collection<Coupon> coupons;

	/**
	 * Simple C'tor when no object needed.
	 */
	public Company() {
	}

	/**
	 * Company C'tor.
	 *
	 * @param id       Company ID - Auto-generated by DB
	 * @param name     Company name
	 * @param password Company password - Converted to hash by
	 *                 {@code CryptoHashAlgorithms}
	 * @param email    Company email
	 */
	public Company(long id, String name, String password, String email) {
		this.id = id;
		this.name = name;
		this.password = password;
		this.email = email;
	}

	/**
	 * Takes the received password and hash it.
	 *
	 * @param password Company password - Set password received by user
	 * 
	 * @throws CouponSystemExceptions
	 */
	public void setPassword(String password) throws CouponSystemExceptions {

		CryptoHashAlgorithms CHA = new CryptoHashAlgorithms();
		try {
			password = CHA.hashPassword(password.getBytes(), "SHA-256");
		} catch (CryptoHashException e) {
			throw new CryptoHashException("Failed to hash the password");
		}
		this.password = password;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Collection<Coupon> getCoupons() {
		return coupons;
	}

	public void setCoupons(Collection<Coupon> coupons) {
		this.coupons = coupons;
	}

	public String getPassword() {
		return password;
	}

	@Override
	public String toString() {
		return "Company [id=" + id + ", name=" + name + ", password=" + password + ", email=" + email + ", coupons="
				+ coupons + ", getId()=" + getId() + ", getName()=" + getName() + ", getEmail()=" + getEmail()
				+ ", getCoupons()=" + getCoupons() + ", getPassword()=" + getPassword() + ", getClass()=" + getClass()
				+ ", hashCode()=" + hashCode() + ", toString()=" + super.toString() + "]";
	}

}
