package coupon.sys.core.beans;

import java.io.Serializable;
import java.sql.Date;

/**
 * This class is for creating the coupon object to use with the different
 * company and customer related methods.
 * 
 * @author Julio Hernan Trajtemberg
 * @version 1.0 September 18, 2018.
 */

public class Coupon implements Serializable {

	/** The logger */
//	private static final Logger logger = LoggerFactory.getLogger(Coupon.class);
	
	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** The id. */
	private long id;

	/** The title. */
	private String title;

	/** The start date. */
	private Date startDate;

	/** The end date. */
	private Date endDate;

	/** The amount. */
	private int amount;

	/** The type. */
	private CouponType type;

	/** The message. */
	private String message;

	/** The price. */
	private double price;

	/** The image. */
	private String image;

	/**
	 * Simple C'tor when no object needed.
	 */
	public Coupon() {

	}

	/**
	 * Coupon C'tor.
	 *
	 * @param id        Coupon ID - Auto-generated by DB
	 * @param title     Coupon title
	 * @param startDate Coupon start date
	 * @param endDate   Coupon end date
	 * @param amount    Coupon amount - quantity of same coupons
	 * @param type      Coupon type - {@code CouponType}
	 * @param message   Coupon message - text to describe the coupon
	 * @param price     Coupon price
	 * @param image     Coupon image
	 */
	public Coupon(long id, String title, Date startDate, Date endDate, int amount, CouponType type, String message,
			double price, String image) {

		super();
		this.id = id;
		this.title = title;
		this.startDate = startDate;
		this.endDate = endDate;
		this.amount = amount;
		this.type = type;
		this.message = message;
		this.price = price;
		this.image = image;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Date getStartDate() {
		return startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public int getAmount() {
		return amount;
	}

	public void setAmount(int amount) {
		this.amount = amount;
	}

	public CouponType getType() {
		return type;
	}

	public void setType(CouponType type) {
		this.type = type;
	}

	public String getMessage() {
		return message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public double getPrice() {
		return price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public String getImage() {
		return image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	@Override
	public String toString() {
		return "Coupon [id=" + id + ", title=" + title + ", startDate=" + startDate + ", endDate=" + endDate
				+ ", amount=" + amount + ", type=" + type + ", message=" + message + ", price=" + price + ", image="
				+ image + ", getId()=" + getId() + ", getTitle()=" + getTitle() + ", getStartDate()=" + getStartDate()
				+ ", getEndDate()=" + getEndDate() + ", getAmount()=" + getAmount() + ", getType()=" + getType()
				+ ", getMessage()=" + getMessage() + ", getPrice()=" + getPrice() + ", getImage()=" + getImage()
				+ ", getClass()=" + getClass() + ", hashCode()=" + hashCode() + ", toString()=" + super.toString()
				+ "]";
	}

}
