package coupon.sys.core.beans;

import java.io.Serializable;
import java.util.Collection;

import coupon.sys.core.exceptions.CouponSystemExceptions;
import coupon.sys.core.exceptions.CryptoHashException;
import coupon.sys.core.utils.CryptoHashAlgorithms;

/**
 * This class is for creating the customer object to use with the different
 * customer related methods.
 * 
 * @author Julio Hernan Trajtemberg
 * @version 1.0 September 18, 2018.
 */

public class Customer implements Serializable {

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** The id. */
	private long id;

	/** The name. */
	private String name;

	/** The password. */
	private String password;

	/** The coupons. */
	private Collection<Coupon> coupons;

	/**
	 * Simple C'tor when no object needed.
	 */
	public Customer() {
		super();
	}

	/**
	 * Customer C'tor.
	 *
	 * @param id
	 *            Customer ID - Auto-generated by DB
	 * @param name
	 *            Customer name
	 * @param password
	 *            Customer password - Converted to hash by
	 *            {@code CryptoHashAlgorithms}
	 */
	public Customer(long id, String name, String password) {

		super();
		this.id = id;
		this.name = name;
		this.password = password;
	}

	/**
	 * Takes the received password and hash it.
	 *
	 * @param password
	 *            Customer password - Set password received by user
	 * @throws CouponSystemExceptions
	 */
	public void setPassword(String password) throws CouponSystemExceptions {

		CryptoHashAlgorithms CHA = new CryptoHashAlgorithms();
		try {
			password = CHA.hashPassword(password.getBytes(), "SHA-256");
		} catch (CryptoHashException e) {
			throw new CryptoHashException("Failed to hash the password");
		}
		this.password = password;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Collection<Coupon> getCoupons() {
		return coupons;
	}

	public void setCoupons(Collection<Coupon> coupons) {
		this.coupons = coupons;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	public String getPassword() {
		return password;
	}

	@Override
	public String toString() {
		return "Customer [id=" + id + ", name=" + name + ", password=" + password + ", coupons=" + coupons
				+ ", getId()=" + getId() + ", getName()=" + getName() + ", getCoupons()=" + getCoupons()
				+ ", getPassword()=" + getPassword() + ", getClass()=" + getClass() + ", hashCode()=" + hashCode()
				+ ", toString()=" + super.toString() + "]";
	}

}
